language: python
python:
  - "3.4"
  - "2.7"
install:
  - pip install coverage
  - pip install "pytest>=3.1"
  - pip install mock
  - pip install pytest-cov
  - pip install -U setuptools
script:
  - python setup.py install
  - pytest --cov pycldf 
before_install:
  pip install codecov
after_success:
  codecov
